### ISSUE TITLE
Cannot create PyString with non-byte value

### ISSUE THREAD

**Issue by ari-vedant-jain** [vedantja/HousingPriceModelServing#2]
Traceback (most recent call last):
  File "./housing.py", line 5, in <module>
    from flask import Flask, abort, request, jsonify
  File "/root/jython-2.7.0/Lib/site-packages/flask/__init__.py", line 17, in <module>
    from werkzeug.exceptions import abort
  File "/root/jython-2.7.0/Lib/site-packages/werkzeug/__init__.py", line 20, in <module>
    from werkzeug._compat import iteritems
  File "/root/jython-2.7.0/Lib/site-packages/werkzeug/_compat.py", line 10, in <module>
    import builtins
  File "/root/jython-2.7.0/Lib/site-packages/werkzeug/_compat.py", line 10, in <module>
    import builtins
java.lang.IllegalArgumentException: Cannot create PyString with non-byte value
	at org.python.core.PyString.<init>(PyString.java:64)
	at org.python.core.PyString.<init>(PyString.java:70)
	at org.python.modules.zipimport.zipimporter.readZipFile(zipimporter.java:404)
	at org.python.modules.zipimport.zipimporter.readDirectory(zipimporter.java:366)
	at org.python.modules.zipimport.zipimporter.zipimporter___init__(zipimporter.java:118)
	at org.python.modules.zipimport.zipimporter.zipimporter___init__(zipimporter.java:84)
	at org.python.modules.zipimport.zipimporter$exposed___new__.createOfType(Unknown Source)
	at org.python.core.PyOverridableNew.new_impl(PyOverridableNew.java:12)
	at org.python.core.PyType.invokeNew(PyType.java:494)
	at org.python.core.PyType.type___call__(PyType.java:1706)
	at org.python.core.PyType.__call__(PyType.java:1696)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.imp.getPathImporter(imp.java:480)
	at org.python.core.imp.find_module(imp.java:530)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_first(imp.java:870)
	at org.python.core.imp.import_module_level(imp.java:972)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1081)
	at werkzeug._compat$py.f$0(/tmp/pip_build_root/Werkzeug/werkzeug/_compat.py:198)
	at werkzeug._compat$py.call_function(/tmp/pip_build_root/Werkzeug/werkzeug/_compat.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.PyModule.impAttr(PyModule.java:106)
	at org.python.core.imp.import_next(imp.java:842)
	at org.python.core.imp.import_logic(imp.java:904)
	at org.python.core.imp.import_module_level(imp.java:978)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at werkzeug$py.f$0(/tmp/pip_build_root/Werkzeug/werkzeug/__init__.py:151)
	at werkzeug$py.call_function(/tmp/pip_build_root/Werkzeug/werkzeug/__init__.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_first(imp.java:870)
	at org.python.core.imp.import_module_level(imp.java:972)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at flask$py.f$0(/tmp/pip_build_root/Flask/flask/__init__.py:49)
	at flask$py.call_function(/tmp/pip_build_root/Flask/flask/__init__.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.imp.createFromCode(imp.java:436)
	at org.python.core.imp.createFromPyClass(imp.java:236)
	at org.python.core.imp.createFromPyClass(imp.java:205)
	at org.python.core.imp.loadFromSource(imp.java:651)
	at org.python.core.imp.find_module(imp.java:543)
	at org.python.core.imp.import_next(imp.java:840)
	at org.python.core.imp.import_module_level(imp.java:959)
	at org.python.core.imp.importName(imp.java:1062)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:431)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importFromAs(imp.java:1156)
	at org.python.core.imp.importFrom(imp.java:1132)
	at org.python.pycode._pyx0.f$0(./housing.py:25)
	at org.python.pycode._pyx0.call_function(./housing.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:167)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1386)
	at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
	at org.python.util.jython.run(jython.java:362)
	at org.python.util.jython.main(jython.java:142)

java.lang.IllegalArgumentException: java.lang.IllegalArgumentException: Cannot create PyString with non-byte value

**Comment by ari-vedant-jain** [comment]
This was fixed when upgraded to Jython v2.7.1
